### ISSUE TITLE
HTTP 403 Forbidden

### ISSUE THREAD

**Issue by divinity76** [jesec/SamFirm.NET#2]
```
>win-x64-single.exe --model SM-F916N -r KOO

  Model: SM-F916N
  Region: KOO

  Latest version:
    PDA: F916NKSU2KWH7
    CSC: F916NOKR2KWH7
    MODEM: F916NKSU2KWH1

  OS: T(Android 13)
  Filename: SM-F916N_4_20230810091220_qnkwxvnnm8_fac.zip.enc4
  Size: 7273318080 bytes
  Logic Value: 7llh51xh604fpkex
  Description:
    https://doc.samsungmobile.com/SM-F916N/KOO/doc.html

C:\Users\hans\Downloads\rooting\SM-F916N_KOO
Error GetResponseFUS() -> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at SamFirm.Utils.FUSClient.GetFUSResponse(WebRequest wr)
Error DownloadBinary(): 403
>echo %ERRORLEVEL%
0
```

**Comment by divinity76** [comment]
oops my bad, fixed by https://github.com/jesec/SamFirm.NET/pull/1

(but fix is un-released)
