### ISSUE TITLE
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.    at SamFirm.Program.Main(String[] args)

### ISSUE THREAD

**Issue by divinity76** [jesec/SamFirm.NET#4]
```
>win-x64-single.exe --model SM-S908B --region EUX

  Model: SM-S908B
  Region: EUX

  Latest version:
    PDA: S908BXXS6CWI1
    CSC: S908BOXM6CWI1
    MODEM: S908BXXU6CWH5
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SamFirm.Program.Main(String[] args)
```

Interestingly doing the same with EUY also crash, but using region BTE does /not/ crash. but all 3 of them supposedly exists, and EUX definitely exists, here is a screenshot from a SM-S908B using EUX: 

![](http://stuff.ratma.net/2023/Screenshot_20231023_002541_Settings.jpg)

```
http://fota-cloud-dn.ospserver.net/firmware/AFG/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MOB/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/VIP/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/O2C/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/EGY/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/BOG/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SFR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/ACR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/ILO/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/INS/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MID/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/TIM/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SKZ/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/AFR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/FWD/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MWD/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/NPL/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/ECT/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/PAK/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/PLS/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/PRT/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SER/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/KSA/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/DKR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/TOP/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MOT/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SIM/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/XFA/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/XFE/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/XFV/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SLK/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SWC/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/TUN/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/TUR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SEK/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/XSG/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/EVR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/CPW/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/TSI/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MET/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/CAU/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/LYS/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MEO/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MSR/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/EUX/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/EUY/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/ILP/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/BKD/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/BTB/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/BTE/SM-S908B/version.xml   : 200
```

**Comment by Martyn911** [comment]
Are you affiliated with the site [SamFirm](https://samfirm.shop/) ?

**Comment by divinity76** [comment]
@Martyn911 nope. just some random guy rooting his S22U

**Comment by Masoud734** [comment]
> ```
> >win-x64-single.exe --model SM-S908B --region EUX
> 
>   Model: SM-S908B
>   Region: EUX
> 
>   Latest version:
>     PDA: S908BXXS6CWI1
>     CSC: S908BOXM6CWI1
>     MODEM: S908BXXU6CWH5
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at SamFirm.Program.Main(String[] args)
> ```
> 
> Interestingly doing the same with EUY also crash, but using region BTE does /not/ crash. but all 3 of them supposedly exists, and EUX definitely exists, here is a screenshot from a SM-S908B using EUX:
> 
> ![](https://camo.githubusercontent.com/e364ff95f595a669b910ffdfa8a47ff991b46cd4fbd3e24987ff5c8fd0c90395/687474703a2f2f73747566662e7261746d612e6e65742f323032332f53637265656e73686f745f32303233313032335f3030323534315f53657474696e67732e6a7067)
> 
> ```
> http://fota-cloud-dn.ospserver.net/firmware/AFG/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MOB/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/VIP/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/O2C/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/EGY/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/BOG/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SFR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/ACR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/ILO/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/INS/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MID/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/TIM/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SKZ/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/AFR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/FWD/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MWD/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/NPL/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/ECT/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/PAK/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/PLS/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/PRT/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SER/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/KSA/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/DKR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/TOP/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MOT/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SIM/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/XFA/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/XFE/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/XFV/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SLK/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SWC/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/TUN/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/TUR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/SEK/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/XSG/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/EVR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/CPW/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/TSI/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MET/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/CAU/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/LYS/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MEO/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/MSR/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/EUX/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/EUY/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/ILP/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/BKD/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/BTB/SM-S908B/version.xml   : 200
> http://fota-cloud-dn.ospserver.net/firmware/BTE/SM-S908B/version.xml   : 200
> ```
