### ISSUE TITLE
Exception: Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by cn-ml** [jesec/SamFirm.NET#7]
```
win-x64.exe -m SM-G950F -r DBT

  Model: SM-G950F
  Region: DBT

  Latest version:
    PDA: G950FXXUCDVI1
    CSC: G950FOXMCDUD1
    MODEM: G950FXXUCDUD1
Unhandled exception. System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at SamFirm.Utils.Crypto.DecryptStringFromBytes(Byte[] cipherText, Byte[] Key)
   at SamFirm.Utils.Auth.DecryptNonce(String nonce)
   at SamFirm.Utils.FUSClient.GetFUSResponse(WebRequest wr)
   at SamFirm.Utils.FUSClient.GenerateNonce()
   at SamFirm.Program.Main(String[] args)
```

**Comment by ghost** [comment]
Same issue. Not usable anymore.
